[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "NarrativeExpansion"
versionNumber = "2.1.0"
description = "MAJOR UPDATE: Interactive NPCs! Adds The Wanderer, Old Engineer, Archivist, Scout, and Oracle NPCs with unique dialogue and behaviors. Plus extended dialogue, lore, and mysteries."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-NarrativeExpansion"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/NarrativeExpansion.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
