[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "NarrativeExpansion"
versionNumber = "2.7.0"
description = "NPCs with AUTHENTIC game character voices! New Sparks Terminal, Paladin Echo, Mirage Hologram, Groundbreaker Monument play real voiced dialogue. Plus 5 custom NPCs with procedural robot voices. Extended dialogue, lore, mysteries."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-NarrativeExpansion"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/NarrativeExpansion.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "./Bundles/mech_companion"
target = "/Bundles/"

[[build.copy]]
source = "./Bundles/robot_sphere"
target = "/Bundles/"

[[build.copy]]
source = "./Bundles/robot_metallic"
target = "/Bundles/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
